try {
  let a;
  console.log(a);
  console.log("Inside try block");
} catch (e) {
  console.log("INside in Catch block");
}
console.log("Hi there");
